---
- name: Execute shell script on remote server to purge Keepalived & HAProxy
  hosts: haproxy
  become: true
  user: root
  tasks:
    - name: Run shell script on remote server to purge Keepalived & HAProxy 
      shell: "sh -c /home/ubuntu/0_HAProxy/purgeHA.sh"
      async: 1
      poll: 0
      ignore_errors: true

